image:
  file: .gitpod.Dockerfile
tasks:
  - name: Running MongoDB
    command: mkdir -p data && mongod --dbpath data
  - name: Install nodemon and start npm
    command: npm i -g nodemon && npm start